#! /bin/bash

BANNER_TEXT="

██     ██ ██ ███████ ██       █████  ███    ██ ██████
██     ██ ██ ██      ██      ██   ██ ████   ██ ██   ██
██  █  ██ ██ █████   ██      ███████ ██ ██  ██ ██   ██
██ ███ ██ ██ ██      ██      ██   ██ ██  ██ ██ ██   ██
 ███ ███  ██ ███████ ███████ ██   ██ ██   ████ ██████


"

# Calculate the width of the terminal window
WIDTH=$(tput cols)

# Set colors
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
RESET=$(tput sgr0)

# Print the banner
printf "%${WIDTH}s\n" | tr ' ' '*'
printf "%*s\n" $(((${#BANNER_TEXT}+WIDTH)/2)) "${RED}${BANNER_TEXT}${RESET}"
printf "%${WIDTH}s\n" | tr ' ' '*'

echo "
Umbau Hilfe ZG 23

"
