#! /bin/bash

BANNER_TEXT="

██     ██ ██ ███████ ██       █████  ███    ██ ██████
██     ██ ██ ██      ██      ██   ██ ████   ██ ██   ██
██  █  ██ ██ █████   ██      ███████ ██ ██  ██ ██   ██
██ ███ ██ ██ ██      ██      ██   ██ ██  ██ ██ ██   ██
 ███ ███  ██ ███████ ███████ ██   ██ ██   ████ ██████


"

# Calculate the width of the terminal window
WIDTH=$(tput cols)

# Set colors
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
RESET=$(tput sgr0)

# Print the banner
printf "%${WIDTH}s\n" | tr ' ' '*'
printf "%*s\n" $(((${#BANNER_TEXT}+WIDTH)/2)) "${RED}${BANNER_TEXT}${RESET}"
printf "%${WIDTH}s\n" | tr ' ' '*'

echo "
Umbau Hilfe ZG 23

"
echo "Bitte wählen sie den Durchmesser aus

"

options="9-11,5 12-13,5  Beenden"
select option in $options; do
                if [ "9-11,5" = $option ]; then
                        echo "   Bei DRM 9-11,5 bitte folgendes beachten:
                        "
                        echo "   Rote Rohre und 9er Lineale "
                        echo "   15er Rohrkasten (rot)
                        "
                        echo "   Achtung bei SW1 -> SW1 Stempel verwenden !!"
                        sleep 2
                        echo "
                        Bitte erneut auswählen"

                elif [ "12-13,5" = $option ]; then
                        echo "   Bei DRM 12-13,5 bitte folgendes beachten:
                        "
                        echo "   Blaue Rohre und 9er Lineale "
                        echo "   20er Rohrkasten (blau)
                        "
                        echo "   Achtung bei SW1 -> SW1 Stempel verwenden !!"
                        sleep 2
                        echo "
                        Bitte erneut auswählen"

                elif [ "Beenden" = $option ]; then
                        echo "
                                                     Viel Erfolg

"
                        sleep 3
                        clear
                        exit
                        fi
done
